# Site settings
title: Varun Agrawal Online
email: varagrawal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the website of Varun Agrawal. Created by yours truly!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://varunagrawal.github.io" # the base hostname & protocol for your site
twitter_username: varagrawal
github_username:  varunagrawal

name: Varun Agrawal
timezone: EST
lsi: true

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax
highlighter: rouge

permalink: pretty

collections:
- collection